services:
  redis-server:
    image: 'redis'
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile_with_redis
    #image: 'm4salemcc/att-docker-repo:latest'
    ports:
      - "5000:5000"
    restart: always

    #add volume to load the iris data to the /mnt/data folder
    volumes:
      - ./data:/mnt/data